language: node_js
node_js:
- 0.12
- iojs
env:
  global:
  - secure: OM+SbUzZ/E4pGtj9UZ43Rpu0FN7x/AdmWeG/N4EIUVf8KD7I2NaV/XEf2XLJCAiKCCmG1w9KiarFTNymupi1bxTuCL2qEpnpg846kFcL8pxxRyAe7JnAVYLfCapWDZZEJo4iGv+uabmPNONYB/81kGUvIhcFyXxYzLDCYaFBF7s=
before_script:
- echo "repo_token="$COVERALLS_REPO_TOKEN > .coveralls.yml
script:
- npm test
- npm run codacy
